name: vikas_pasoriya
description: Official Professional App
version: 6.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # कति लेटेस्ट वर्जन

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animate_do: ^3.3.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
