name: vikas_pasoriya_app
description: "Vikas Pasoriya Official App"
version: 1.1.4+14
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0' # मशीन यही मांग रही सै

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  youtube_player_flutter: ^8.1.2
  qr_flutter: 4.1.0

flutter:
  uses-material-design: true
