name: Build APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Master Build
        run: |
          flutter clean
          flutter pub get
          # एंड्राइड फोल्डर रिपेयर
          flutter create . --platforms=android --project-name=vikas_pasoriya
          chmod +x android/gradlew
          # फाइनल बिल्ड
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vikas-official-app
          path: build/app/outputs/flutter-apk/app-release.apk
